### PR TITLE
Update android module

### PR DESCRIPTION
**Pull request by kishormainali**
- compileOptions and kotlinOptions for android
- recreate example projects using latest flutter version
-  min dart sdk to 3.4.1

### CODE REVIEW

**Review by joco1412 — APPROVED** [review]
Good

**Comment by kishormainali** [comment]
> @kishormainali are you able to fix this warning in the same pr?
> 
> > You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

sure i'll update the PR

**Comment by kishormainali** [comment]
@acoutts i've recreated android modules using latest flutter version and updated examples with latest flutter.

**Comment by alpha2048** [comment]
Is this pull request moving forward?
I'm having trouble with old Android settings.

**Comment by kishormainali** [comment]
@acoutts i've updated the PR please check

**Pull request closed without merging**
